services:
  server:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: co-co-gong
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: main
    ports:
      - "8080:8080"
    command: ["sh", "-c", "tail -f /dev/null"]
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: co-co-gong
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: main
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
