spring:
  application:
    name: co-co-gong-server
  profiles:
    group:
      local:
        - local
        - jwt
      test:
        - test
        - jwt
      deploy:
        - deploy
        - jwt
    active: local
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
  paths-to-match: /**
