spring:
  application:
    name: co-co-gong-server
  profiles:
    group:
      test:
        - test
      deploy:
        - deploy
    active: test
  config:
    import: optional:file:.env[.properties]
