spring:
  application:
    name: co-co-gong-server
  profiles:
    group:
      local:
        - local
      test:
        - test
      deploy:
        - deploy
    active: deploy
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
  paths-to-match: /**
